# Generated by Django 4.1.4 on 2022-12-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="image_thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="films/", verbose_name="Miniatura"
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="image_wallpaper",
            field=models.ImageField(
                blank=True, null=True, upload_to="films/", verbose_name="Wallpaper"
            ),
        ),
    ]
