# Generated by Django 4.1.4 on 2022-12-09 19:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import films.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("films", "0002_film_image_thumbnail_film_image_wallpaper"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="average_note",
            field=models.FloatField(
                default=0.0,
                validators=[django.core.validators.MaxValueValidator(10.0)],
                verbose_name="nota media",
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="favorites",
            field=models.IntegerField(default=0, verbose_name="favoritos"),
        ),
        migrations.AlterField(
            model_name="film",
            name="image_thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=films.models.Film.path_to_film,
                verbose_name="Miniatura",
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="image_wallpaper",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=films.models.Film.path_to_film,
                verbose_name="Wallpaper",
            ),
        ),
        migrations.CreateModel(
            name="FilmUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Sin estado"), (1, "Vista"), (2, "Quiero verla")],
                        default=0,
                    ),
                ),
                ("favorite", models.BooleanField(default=False)),
                (
                    "note",
                    models.PositiveSmallIntegerField(
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(10)],
                    ),
                ),
                ("review", models.TextField(null=True)),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="films.film"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["film__title"],
                "unique_together": {("film", "user")},
            },
        ),
    ]
